apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Because Istio sidecar needs to be placed with Prometheus, this needs to be
# some namespace with Istio sidecar enablement.
namespace: monitoring

resources:
  - pa-prometheus-disable-mtls.yaml
  - sidecar-prometheus-istio-collector.yaml
