kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Ref: https://github.com/kubernetes-sigs/kind/releases
  - role: control-plane
    image: kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          certSANs:
            - "127.0.0.1"
            - "172.18.255.210"
  - role: worker
    image: kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419c66f
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 32011
        hostPort: 32011
        protocol: TCP
      - containerPort: 32021
        hostPort: 32021
        protocol: TCP
      - containerPort: 32031
        hostPort: 32031
        protocol: TCP
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        authorization-mode: "AlwaysAllow"
